#!/usr/bin/env bash
# Redirect to another page

sudo apt-get update
sudo apt-get -y install nginx
sudo chown -R "$USER:$USER" /var/www
echo "Hello World!" | sudo tee /var/www/html/index.html
str = "server_name _;\n\trewrite ^\/redirect_me https:\/\/www.segunlawal.dev permanent;"
sudo sed -i "s/$str/" /etc/nginx/sites-enabled/default
service nginx start
