#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
str = str="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.segunlawal.dev permanent;"
sudo sed -i "s/listen 80 default_server;/$str/" /etc/nginx/sites-enabled/default 
