#!/usr/bin/env bash
# This script displays "Best School" 10 times and "Hi" for the 9th iteration

(( count = 0 ))
while ((count < 10)); do
	echo "Best School"
	if ((count == 8)); then
		echo "Hi";
	fi
	(( count++ ))
done
