#!/usr/bin/env bash
# This script runs Nginx as the nginx user

sudo chmod u+rw /etc/nginx/nginx.conf
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
sudo service nginx restart
